### ISSUE TITLE
installation fails

### ISSUE THREAD

**Issue by wiiikiii** [noahlh/celestite#3]
I added 

    celestite:
        github: noahlh/celestite
        version: ~> 0.1.2

and I also tried

    celestite:
       github: noahlh/celestite

the result is always

    # shards update
    ...
    Fetching https://github.com/noahlh/celestite.git
    Failed git ls-tree -r --full-tree --name-only v0.1.1 -- shard.yml (). Maybe a commit, branch or file doesn't exist?

Is there a solution?

**Comment by noahlh** [comment]
Sorry about that!  I’ll take a look ASAP and post back what I discover.

**Comment by noahlh** [comment]
I think I have a version mismatch somewhere — that 0.1.1 in the error message is a clue. I’ll patch and test.

**Comment by noahlh** [comment]
@wiiikiii ok should work now!  I wasn't following proper semver tagging rules for releases and I didn't realize that's a hard dependency for shard installation to work properly.  Added a new release in the proper format for v0.1.2.  LMK if any issues.

**Comment by noahlh** [comment]
Closing for now - let me know if this still an issue!
